# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ amar5607-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name : chumma
      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ../private.key -o StrictHostKeyChecking=no" /home/runner/work/maven_testing_1/maven_testing_1/maven_testing_1/testing1/target/ root@172.42.42.101:/root
      env:
          SSH_PRIVATE_KEY: ${{secrets.secret_key}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
