# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ amar5607-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: amar5607/maven_testing_1@master
      with:
        switches: -avzr --delete
        path: public/
        remote_path: /home/vagrant/maven_deployment/
        remote_host: 172.42.42.101
        remote_port: 22
        remote_user: vagrant
        remote_key: ${{ secrets.KEYS }}
