# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ amar5607-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8.
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v2
    - name: Build with Maven1
      run: |
            mvn -B package --file pom.xml
            mkdir -p ~/.ssh/
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/my_ssh_key
            cp -r ~/.ssh/my_ssh_key ~/.ssh/mysshkey.pem
            chmod 700 ~/.ssh
            ls -lrt ~/.ssh
            chmod 400 ~/.ssh/mysshkey.pem
            ls -lrt ~/.ssh/mysshkey.pem
            ssh -i ~/.ssh/mysshkey.pem  gitaction@54.190.231.180
            ls -lrt
      env:
          SSH_PRIVATE_KEY: ${{secrets.SECRET_KEY}}
