# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ amar5607-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8.
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
            mvn -B package --file pom.xml
    - uses: actions/checkout@v2
    - name: Checkout source codes
      run: |
          mkdir -p ~/.ssh/
          mkdir -p ~/jar_file/
          cp -r /home/runner/work/maven_testing_1/maven_testing_1/maven_testing_1/testing1/target/ ~/jar_file/
          ls -lrt ~/.ssh
          ls -lrt ~/jar_file/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          ls -lrt ~/.ssh/
          cat ~/.ssh/private.key
          rsync -avz -e "ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no" /home/runner/work/maven_testing_1/maven_testing_1/maven_testing_1/testing1/target/ root@172.42.42.101:/root/
      env:
          SSH_PRIVATE_KEY: ${{secrets.secret_key}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
