# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ amar5607-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8.
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/checkout@v2
    - name: Build with Maven1
      run: |
            mvn -B package --file pom.xml
            mkdir -p ~/.ssh/
            cp -r ./tmp_file.pem ~/.ssh/
            chmod 400 ~/.ssh/tmp_file.pem
            ls -lrt ~/.ssh
            hostname -i
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/tmp_file.pem  gitaction@54.190.231.180 uptime
            scp -r ~/.ssh/tmp_file.pem /home/runner/work/maven_testing_1/maven_testing_1/target/helloworld-1.1.jar gitaction@54.190.231.180:/home/gitaction 
            ls -lrt
      env:
          SSH_PRIVATE_KEY: ${{secrets.SECRET_KEY}}
